{{- if .Values.ingress.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: moonpay-frontend-config
  namespace: {{ .Values.namespace.name }}
spec:
  sslPolicy: {{ .Values.ingress.sslPolicyName }}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
