namespace:
  name: moonpay-prod
  environment: prod
  app: moonpay

app:
  name: moonpay-app
  replicaCount: 2
  image:
    repository: gcr.io/moonpay-playground/devops-challenge
    tag: latest
    pullPolicy: Always
  port: 3000
  # K8s secret created by the deploy workflow from GCP Secret Manager.
  # All keys in this secret are injected as env vars into the app container.
  secretName: moonpay-app-secrets
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: gce
  host: moonpay.svilbert.app
  staticIpName: moonpay-lb-ip-prod
  sslCertName: moonpay-ssl-cert-prod
  sslPolicyName: moonpay-ssl-policy-prod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: moonpay-lb-ip-prod
    ingress.gcp.kubernetes.io/pre-shared-cert: moonpay-ssl-cert-prod
    kubernetes.io/ingress.class: gce
    networking.gke.io/v1beta1.FrontendConfig: moonpay-frontend-config
